### ISSUE TITLE
Suchfenster: Inventarnummer, Geräteart, Hersteller, Aufstellungsort, Status, Datum, Verfasser

### ISSUE THREAD

**Issue by EuroBBW-TN1** [Euro-BBW-FIA1/KlaustechnikInv#5]

**Comment by Hickotine** [comment]
Nutzt ebenfalls "Products", Funktion heißt ProductSearch

**Comment by Hickotine** [comment]
SelColProducts stored procedure hinzugefügt, Parameter @ColName für Name der Spalte, bei Bedarf implementieren
